### ISSUE TITLE
Error in SSHKey intialization in non-strict mode with DSA key non-standard bit length

### ISSUE THREAD

**Issue by benkonrath** [ojarva/python-sshpubkeys#54]
I would expect this key to work in non-strict mode. It looks like the error comes from a check in the cryptography library. Maybe this was working in earlier versions of cryptography?

```
from sshpubkeys import SSHKey
short_dss_key = 'ssh-dss AAAAB3NzaC1kc3MAAACAd+4e5gmIwRZ6ndOdZ6tYFjQUw6bvNhvxooYiPYkygvalV0HPiC80bHZ90p0xnG8h' \
                'bzbC1fSK2V8dqtSou11VFXpffKsvtTW4gFv8W/DfOU34pU/RShHWhWQwidvyxAmwbhX5pGey6lmN+EBaDq9C/zAxB559' \
                '7ABTQtWRKnIlEUcAAAAVALGWA77DZ+oYthZyeAlHtvuTdnvHAAAAgEGg/LZkUXf0V7MGNWpYTXky19l3QgoNMj8KjDcx' \
                'vPXAMBqZte2nuDueD6V4buz7TdbsrtRfW0r8NzqmsvOOdIagb78U7pzFJcgDdUFCM0X32j0FAWOM9khipAr/ZJcZLapr' \
                'aRfKAlUzLPhsL9GpQrfTKqeTb1U18xE6lUQztfiNAAAAgBMV/Jwk5Jx5zzXvINesaO0+jCmhjZNM8FTkiHi+jQmmbNl3' \
                'NMHoG54pXK0i9e/6VLO/d7elJHZWyLyNi5kGn1UimWQIOR4CPJYuOs/PlrdrKiAY+HIzLtQZ0OO9vGkTISvc+P8KWcSt' \
                'OlFAvu7DiQ3cWxQqcDZ/VPl7LpFXSGOU foo'
SSHKey(short_dss_key, strict=False, disallow_options=False, skip_option_parsing=True)

Traceback (most recent call last):
  File "/home/ben/Development/project/hypernodedb/tests/models/test_ssh_key.py", line 48, in test_ssh_key_properties_return_an_empty_string_when_public_key_is_invalid
    SSHPubKey(short_dss_key, strict=False, disallow_options=False, skip_option_parsing=True)
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/sshpubkeys/keys.py", line 132, in __init__
    self.parse(keydata)
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/sshpubkeys/keys.py", line 433, in parse
    key_data_length = self._process_key(self._decoded_key[current_position:])
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/sshpubkeys/keys.py", line 389, in _process_key
    return self._process_ssh_dss(data)
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/sshpubkeys/keys.py", line 344, in _process_ssh_dss
    self.dsa = DSAPublicNumbers(data_fields["y"], dsa_parameters).public_key(default_backend())
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 206, in public_key
    return backend.load_dsa_public_numbers(self)
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 615, in load_dsa_public_numbers
    dsa._check_dsa_parameters(numbers.parameter_numbers)
  File "/home/ben/Development/project/env/lib64/python3.4/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 132, in _check_dsa_parameters
    raise ValueError("p must be exactly 1024, 2048, or 3072 bits long")
ValueError: p must be exactly 1024, 2048, or 3072 bits long
```

Library versions:
```
cryptography==2.3.1
sshpubkeys==3.1.0
```

Do you have an idea on a workaround for this?

**Comment by ojarva** [comment]
No I don't - there are different standards for what is allowed as DSA key length, and underlying library (`cryptography`) wants to have 1024, 2048 or 3072. OpenSSH on the other hand allows other values as well.

I don't personally use (or allow using) DSA keys, so I don't have personal interest in improving this part of the code. In general, if you need to work with a large collection of existing keys, it might be better to run `ssh-keygen` in a sandbox for validating keys, as that will more or less ensure what you have is compatible with OpenSSH (at least some version(s) of it, new algorithms are added, and old, short keys are deprecated every now and then).
